Add presale A/B/G contracts and sHBT
HybridProtocol/hybrid-protocol pull request #1
Opened 2020-09-29 20:33 UTC by nbailo

2020-09-30 15:06 UTC, Aksonov-Artem commented on contracts/presale/Presale.sol
> +        require(block.number > startBlock + duration, "Prensale: INVALID_DATE");
I think that "Presale: INVALID_DATE" will do better  than "Prensale: INVALID_DATE".

2020-10-01 11:01 UTC, a-melnichuk requested changes

2020-10-01 11:01 UTC, a-melnichuk commented on libraries/PresaleConstants.sol
> +    uint public constant HONE = 10**18;
`HONE` -> `ONE_HBT_IN_WEI`

2020-10-01 11:01 UTC, a-melnichuk commented on contracts/ServiceHybridToken.sol
> +    uint internal alphaTokensaleLimit = PresaleConstants.ALPHA_PRESALE_LIMIT; // 3% of total supply
You don't need `alphaTokensaleLimit`, since it would use additional storage. Use `PresaleConstants.ALPHA_PRESALE_LIMIT` directly

2020-10-01 11:01 UTC, a-melnichuk commented on contracts/ServiceHybridToken.sol
> +    uint internal betaTokensaleLimit = PresaleConstants.BETA_PRESALE_LIMIT;   // 5% of total supply
You don't need `betaTokensaleLimit`, since it would use additional storage. Use `PresaleConstants.BETA_PRESALE_LIMIT` directly

2020-10-01 11:01 UTC, a-melnichuk commented on contracts/ServiceHybridToken.sol
> +    uint internal gammaTokensaleLimit = PresaleConstants.GAMMA_PRESALE_LIMIT; // 4% of total supply
You don't need `gammaTokensaleLimit `, since it would use additional storage. Use `PresaleConstants.GAMMA_PRESALE_LIMIT` directly

2020-10-01 11:01 UTC, a-melnichuk commented on contracts/ServiceHybridToken.sol
> +    address internal alphaTokensale;
Make it private, if you would not inherit from this contract.

2020-10-01 11:01 UTC, a-melnichuk commented on contracts/ServiceHybridToken.sol
> +    address internal betaTokensale;
Make it private, if you would not inherit from this contract.

2020-10-01 11:01 UTC, a-melnichuk commented on contracts/ServiceHybridToken.sol
> +    address internal gammaTokensale;
Make it private, if you would not inherit from this contract.

2020-10-01 11:01 UTC, a-melnichuk commented on contracts/ServiceHybridToken.sol
> +contract ServiceHybridToken is ERC20, Ownable, Whitelist {
`s` in `sHBT` stands for 'Sale Hybrid Token'

2020-10-01 11:01 UTC, a-melnichuk commented on contracts/ServiceHybridToken.sol
> +    string internal constant NAME = "Service Hybrid Token";
`s` in `sHBT` stands for 'Sale Hybrid Token'

2020-10-01 11:01 UTC, a-melnichuk commented on interfaces/IServiceHybridToken.sol
> +interface IServiceHybridToken is IERC20 {
`IServiceHybridToken` -> `ISaleHybridToken`

2020-10-01 11:01 UTC, a-melnichuk commented on contracts/presale/Presale.sol
> +        assert(_amountUSDC <= purchasedLimit.sub(purchasedAmountOf[msg.sender]));
Replace this logic with your `TODO`

2020-10-01 11:01 UTC, a-melnichuk commented on contracts/presale/Presale.sol
> +    function _buy(uint _amountUSDC) internal {
Would it be used internally somehow? If not, we can make this method external and remove code duplication in Alpha, Beta and Gamma contracts.

2020-10-01 11:01 UTC, a-melnichuk commented on contracts/presale/Presale.sol
> +        // TODO: This check probably could be removed for optimization
Correct, `transferFrom` would throw otherwise. Let's remove this check.

2020-10-05 06:51 UTC, a-melnichuk approved these changes

2020-10-05 15:07 UTC, merged