HP-28 - Test xHBT staking
HybridProtocol/hybrid-protocol pull request #10
Opened 2020-11-02 01:30 UTC by kampod

2020-11-03 15:07 UTC, nbailo approved these changes

2020-11-04 20:33 UTC, kampod commented
Update contract IndexStaking.sol (added checks in 'deposit' function, now could not deposit after past contact duration)

2020-11-05 10:51 UTC, Aksonov-Artem approved these changes

2020-11-06 15:28 UTC, a-melnichuk requested changes

2020-11-06 15:28 UTC, a-melnichuk commented on test/indexStaking/indexStaking.ts
> +  const provider = new MockProvider({
MockProvider doesn't properly show stacktrackes and console.logs. Don't use it.

2020-11-09 14:06 UTC, merged