HP-41 - Add presale contracts
HybridProtocol/hybrid-protocol pull request #13
Opened 2020-11-24 03:25 UTC by nbailo

2020-11-24 17:02 UTC, Aksonov-Artem commented on presale/README.md
> +At first need to get factory for Configurable Right Pool creation. It avaiable by address in **Rinkeby** testnet
Check and update this line, pls.

2020-11-25 14:07 UTC, a-melnichuk approved these changes

2020-11-26 14:14 UTC, a-melnichuk approved these changes

2020-11-27 14:12 UTC, a-melnichuk requested changes
Use proper zero address
`0x0000000000000000000000000000000000000000`

2020-11-30 14:08 UTC, a-melnichuk approved these changes

2020-11-30 14:09 UTC, Aksonov-Artem approved these changes

2020-11-30 14:09 UTC, merged