Initial implementation of index token
HybridProtocol/hybrid-protocol pull request #3
Opened 2020-10-07 13:33 UTC by nbailo

2020-10-07 16:40 UTC, a-melnichuk requested changes

2020-10-07 16:40 UTC, a-melnichuk commented on contracts/IndexHybridToken.sol
> +        emit CompositionUpdated();
`emit CompositionUpdated()` -> `emit CompositionUpdated(_assets, _weights)`

2020-10-08 05:36 UTC, a-melnichuk approved these changes

2020-10-08 05:36 UTC, a-melnichuk commented on contracts/IndexHybridToken.sol
> +    function _addAsset(bytes8 _symbol, uint16 _weight) private onlyWhitelisted {
Find having this internal two-line function unnecessary.

2020-10-09 07:25 UTC, Aksonov-Artem approved these changes

2020-10-09 07:31 UTC, a-melnichuk approved these changes

2020-10-09 07:35 UTC, merged