HP-34 - Add new fields to createProposal method
HybridProtocol/hybrid-protocol pull request #9
Opened 2020-10-29 14:31 UTC by nbailo

2020-10-29 14:40 UTC, a-melnichuk requested changes

2020-10-29 14:40 UTC, a-melnichuk commented on contracts/IndexGovernance.sol
>          emit ProposalCreated(_assets, _weights, _duration, msg.sender);
Emitted event must also include these fields. Otherwise, serve development would not be able to properly show the  history of voting.

2020-10-29 15:43 UTC, a-melnichuk approved these changes

2020-10-31 14:20 UTC, Aksonov-Artem approved these changes

2020-10-31 14:21 UTC, merged